In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/Finetuning_Llama_3.1/HSCodeMaster v3.2.xlsx")

In [ ]:
import pandas as pd

df = pd.read_excel("/content/HSCodeMaster v3.2.xlsx", dtype=str)
pd.set_option('display.max_colwidth', None)

In [ ]:
df.head(10)

,OldHSCode,NewHSCode,LongDescAr,LongDescEn,Unit,Consignment,StatisticalQtyUnit,IS_Vehicle,CDM_Priority,DutyPercentage,AltDutyPercentage,ServiceCharge,Exemption,SpecificDuty,SpecificDutyQty,VGNMat
0,01012110,010121100001,خيول اصيلة الانسال من اصل عربي - ذكور خيول من اصل عربي للأنسال,Live pure-bred breeding horses of Arabian breed - Of Arab breed males,القيمةVALUE,Normal,Kilograms,No,Medium,0,0,0,NaN,NaN,NaN,New Sub
1,01012110,010121100002,خيول اصيلة الانسال من اصل عربي - إناث خيول من أصل عربي للأنسال,Live pure-bred breeding horses of Arabian breed - Of Arab breed females,القيمةVALUE,Normal,Kilograms,No,Medium,0,0,0,NaN,NaN,NaN,New Sub
2,01012190,010121900001,خيول اصيلة الانسال ما عدا الخيول التي من اصل عربي - ذكور خيول من أصل غير عربي للأنسال,Other live pure-bred breeding horses other than of Arabian breed. - Of non-Arab breed males,القيمةVALUE,Normal,Pieces/Units,No,Medium,0,0,0,NaN,NaN,NaN,New Sub
3,01012190,010121900002,خيول اصيلة الانسال ما عدا الخيول التي من اصل عربي - إناث خيول من أصل غير عربي للأنسال,Other live pure-bred breeding horses other than of Arabian breed. - Of non-Arab breed females,القيمةVALUE,Normal,Pieces/Units,No,Medium,0,0,0,NaN,NaN,NaN,New Sub
4,01012910,010129100001,خيول رياضه من أصل غير عربي للرياضة,Live sport horses other than pur- bred breeding animals - Males of Arab breed for sport,القيمةVALUE,Normal,Pieces/Units,No,Medium,0,0,0,NaN,NaN,NaN,New Sub
5,01012910,010129100002,خيول رياضه ما عدا الخيول التي من اصل عربي - إناث خيول من أصل عربي للرياضة,Live sport horses other than pur- bred breeding animals - Females of Arab breed for sport,القيمةVALUE,Normal,Pieces/Units,No,Medium,0,0,0,NaN,NaN,NaN,New Sub
6,01012910,010129100003,خيول رياضه ما عدا الخيول التي من اصل عربي - ذكور خيول من أصل غير عربي للرياضة,Live sport horses other than pur- bred breeding animals - Males of non-Arab breed for sport,القيمةVALUE,Normal,Pieces/Units,No,Medium,0,0,0,NaN,NaN,NaN,New Sub
7,01012910,010129100004,خيول رياضه ما عدا الخيول التي من اصل عربي - إناث خيول من أصل غير عربي للرياضة,Live sport horses other than pur- bred breeding animals - Females of non-Arab breed for sport,القيمةVALUE,Normal,Pieces/Units,No,Medium,0,0,0,NaN,NaN,NaN,New Sub
8,01012920,010129200001,خيول صغيرة الحجم (بوني) - خيول صغيرة الجسم (بوني) ذكور,live ponies other than pure- bred breeding animals - Ponies (males),القيمةVALUE,Normal,Pieces/Units,No,Medium,0,0,0,NaN,NaN,NaN,New Sub
9,01012920,010129200002,خيول صغيرة الحجم (بوني) - خيول صغيرة الجسم (بوني) إناث,live ponies other than pure- bred breeding animals - Ponies (females),القيمةVALUE,Normal,Pieces/Units,No,Medium,0,0,0,NaN,NaN,NaN,New Sub

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13449 entries, 0 to 13448
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   OldHSCode           13449 non-null  object
 1   NewHSCode           13449 non-null  object
 2   LongDescAr          13449 non-null  object
 3   LongDescEn          13449 non-null  object
 4   Unit                13393 non-null  object
 5   Consignment         13448 non-null  object
 6   StatisticalQtyUnit  13449 non-null  object
 7   IS_Vehicle          13449 non-null  object
 8   CDM_Priority        13449 non-null  object
 9   DutyPercentage      13449 non-null  object
 10  AltDutyPercentage   13449 non-null  object
 11  ServiceCharge       13449 non-null  object
 12  Exemption           7106 non-null   object
 13  SpecificDuty        11074 non-null  object
 14  SpecificDutyQty     10834 non-null  object
 15  VGNMat              13449 non-null  object
dtypes: object(16)
memory usage: 1.6+ MB

In [ ]:
df.drop(["Unit","Consignment","IS_Vehicle","CDM_Priority","VGNMat"], axis = 1, inplace = True)

In [ ]:
df.drop(["LongDescAr"], axis = 1, inplace = True)

In [ ]:
df.head(2)

,OldHSCode,NewHSCode,LongDescEn,StatisticalQtyUnit,DutyPercentage,AltDutyPercentage,ServiceCharge,Exemption,SpecificDuty,SpecificDutyQty
0,01012110,010121100001,Live pure-bred breeding horses of Arabian breed - Of Arab breed males,Kilograms,0,0,0,NaN,NaN,NaN
1,01012110,010121100002,Live pure-bred breeding horses of Arabian breed - Of Arab breed females,Kilograms,0,0,0,NaN,NaN,NaN

In [ ]:
df.describe()

,OldHSCode,NewHSCode,LongDescEn,StatisticalQtyUnit,DutyPercentage,AltDutyPercentage,ServiceCharge,Exemption,SpecificDuty,SpecificDutyQty
count,13449,13449,13449,13449,13449,13449,13449,7106,11074,10834
unique,7911,13449,13283,11,5,5,2,22,7,3
top,30024990,980200200000,Other,Kilograms,5,5,0,0,0,0
freq,64,1,38,10278,11776,12735,13021,6229,11038,10814

In [ ]:
df = df.fillna("0")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13449 entries, 0 to 13448
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   OldHSCode           13449 non-null  object
 1   NewHSCode           13449 non-null  object
 2   LongDescEn          13449 non-null  object
 3   StatisticalQtyUnit  13449 non-null  object
 4   DutyPercentage      13449 non-null  object
 5   AltDutyPercentage   13449 non-null  object
 6   ServiceCharge       13449 non-null  object
 7   Exemption           13449 non-null  object
 8   SpecificDuty        13449 non-null  object
 9   SpecificDutyQty     13449 non-null  object
dtypes: object(10)
memory usage: 1.0+ MB

In [ ]:
df.head()

,OldHSCode,NewHSCode,LongDescEn,StatisticalQtyUnit,DutyPercentage,AltDutyPercentage,ServiceCharge,Exemption,SpecificDuty,SpecificDutyQty
0,01012110,010121100001,Live pure-bred breeding horses of Arabian breed - Of Arab breed males,Kilograms,0,0,0,0,0,0
1,01012110,010121100002,Live pure-bred breeding horses of Arabian breed - Of Arab breed females,Kilograms,0,0,0,0,0,0
2,01012190,010121900001,Other live pure-bred breeding horses other than of Arabian breed. - Of non-Arab breed males,Pieces/Units,0,0,0,0,0,0
3,01012190,010121900002,Other live pure-bred breeding horses other than of Arabian breed. - Of non-Arab breed females,Pieces/Units,0,0,0,0,0,0
4,01012910,010129100001,Live sport horses other than pur- bred breeding animals - Males of Arab breed for sport,Pieces/Units,0,0,0,0,0,0

# Final dataset

In [ ]:
import json

records = []

for _, row in df.iterrows():
    old_hs = str(row.get("OldHSCode", "")).strip()
    new_hs = str(row.get("NewHSCode", "")).strip()
    desc_en = str(row.get("LongDescEn", "")).strip()

    # Numeric fields: convert safely
    def to_float(val):
        try:
            return float(val)
        except:
            return 0.0

    unit = str(row.get("StatisticalQtyUnit", "")).strip()
    duty = to_float(row.get("DutyPercentage", 0))
    alt_duty = to_float(row.get("AltDutyPercentage", 0))
    service = to_float(row.get("ServiceCharge", 0))
    exemption = to_float(row.get("Exemption", 0))
    spec_duty = to_float(row.get("SpecificDuty", 0))
    spec_qty = to_float(row.get("SpecificDutyQty", 0))

    # Assistant output as CLEAN JSON
    assistant_json = {
        "NewHSCode": new_hs,
        "OldHSCode": old_hs,
        "StatisticalQtyUnit": unit,
        "DutyPercentage": duty,
        "AltDutyPercentage": alt_duty,
        "ServiceCharge": service,
        "Exemption": exemption,
        "SpecificDuty": spec_duty,
        "SpecificDutyQty": spec_qty
    }

    sample = {
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are an HS Code classification assistant. "
                    "Always provide the New HS Code clearly and accurately along with related attributes."
                )
            },
            {
                "role": "user",
                "content": f"Item description: {desc_en}. Provide all HS details in JSON format."
            },
            {
                "role": "assistant",
                "content": json.dumps(assistant_json, ensure_ascii=False)
            }
        ]
    }

    records.append(sample)

output_file = "train.jsonl"

with open(output_file, "w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

print(f"✅ Fine-tuning dataset created successfully: {output_file}")
print(f"Total samples: {len(records)}")

hscode only

In [ ]:
new_hs = "_".join([new_hs[i:i+4] for i in range(0, len(new_hs), 4)])

In [ ]:
import json
import pandas as pd

records = []

# Assuming df is your DataFrame containing all HS code data
for _, row in df.iterrows():
    new_hs = str(row.get("NewHSCode", "")).strip()
    desc_en = str(row.get("LongDescEn", "")).strip()
    new_hs = "_".join([new_hs[i:i+4] for i in range(0, len(new_hs), 4)])
    desc_en = desc_en.lower()



    # Assistant output: only HS code
    sample = {
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are an HS Code classification assistant."
                    #"Given an item description, output the correct 12-digit HS code in 4+4+4 format"
                )
            },
            {
                "role": "user",
                "content": f"Item description: {desc_en}"
            },
            {
                "role": "assistant",
                "content": f"hs code: {new_hs}"
            }
        ]
    }

    # Append each record **twice** for duplication
    records.append(sample)
    records.append(sample.copy())  # duplicate

# Write to JSONL for fine-tuning
output_file = "train.jsonl"

with open(output_file, "w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

print(f"✅ Fine-tuning dataset created successfully: {output_file}")
print(f"Total samples: {len(records)}")

✅ Fine-tuning dataset created successfully: train.jsonl
Total samples: 26898

Encoded hs code

In [ ]:
import json
import pandas as pd

# 2. BUILD ENCODED ID MAP (5-digit sequential numbering)

hs_to_id = {}
id_to_hs = {}

current_id = 1

for _, row in df.iterrows():
    hs_code = str(row.get("NewHSCode", "")).strip()

    # skip invalid rows
    if len(hs_code) == 0:
        continue

    # Assign ID only if not already assigned
    if hs_code not in hs_to_id:
        encoded = str(current_id).zfill(5)    # "00001"
        hs_to_id[hs_code] = encoded
        id_to_hs[encoded] = hs_code
        current_id += 1


# Save lookup tables
with open("hs_to_id.json", "w", encoding="utf-8") as f:
    json.dump(hs_to_id, f, ensure_ascii=False, indent=2)

with open("id_to_hs.json", "w", encoding="utf-8") as f:
    json.dump(id_to_hs, f, ensure_ascii=False, indent=2)

print("✅ Lookup tables created: hs_to_id.json, id_to_hs.json")
print(f"Total unique HS codes: {len(hs_to_id)}")


# 3. CREATE TRAINING DATA WITH ENCODED HSID
records = []

for _, row in df.iterrows():
    desc_en = str(row.get("LongDescEn", "")).strip()
    hs_code = str(row.get("NewHSCode", "")).strip()

    if hs_code not in hs_to_id:
        continue

    encoded_id = hs_to_id[hs_code]   # "00001"

    sample = {
        "messages": [

            {
                "role": "user",
                "content": f"Item description: {desc_en}"
            },
            {
                "role": "assistant",
                "content": f"<HSID>{encoded_id}</HSID>"
            }
        ]
    }

    # Duplicate the sample for more training weight (optional)
    records.append(sample)
    # records.append(sample.copy())   # enable if you want duplication


# Save final JSONL
output_file = "train.jsonl"

with open(output_file, "w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

print(f"✅ Encoded fine-tuning dataset saved: {output_file}")
print(f"Total samples: {len(records)}")

✅ Lookup tables created: hs_to_id.json, id_to_hs.json
Total unique HS codes: 13449
✅ Encoded fine-tuning dataset saved: train.jsonl
Total samples: 13449

XML format

In [ ]:
import json
records = []

for _, row in df.iterrows():
    old_hs = str(row["OldHSCode"]).strip()
    new_hs = str(row["NewHSCode"]).strip()
    desc_en = str(row["LongDescEn"]).strip()

    unit = str(row["StatisticalQtyUnit"]).strip()
    duty = str(row["DutyPercentage"]).strip()
    alt_duty = str(row["AltDutyPercentage"]).strip()
    service = str(row["ServiceCharge"]).strip()
    exemption = str(row["Exemption"]).strip()
    spec_duty = str(row["SpecificDuty"]).strip()
    spec_qty = str(row["SpecificDutyQty"]).strip()

    # --- Assistant output in XML TAG FORMAT ---
    assistant_xml = (
        f"<HS_CODE>{new_hs}</HS_CODE>\n"
        f"<OLD_CODE>{old_hs}</OLD_CODE>\n"
        f"<UNIT>{unit}</UNIT>\n"
        f"<DUTY>{duty}%</DUTY>\n"
        f"<ALT_DUTY>{alt_duty}</ALT_DUTY>\n"
        f"<SERVICE>{service}</SERVICE>\n"
        f"<EXEMPTION>{exemption}</EXEMPTION>\n"
        f"<SPEC_DUTY>{spec_duty}</SPEC_DUTY>\n"
        f"<SPEC_QTY>{spec_qty}</SPEC_QTY>"
    )

    sample = {
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are an HS Code classification assistant. "
                    "Always return the correct HS Code and all related fields in strict XML tags."
                )
            },
            {
                "role": "user",
                "content": f"Item description: {desc_en}. Provide full HS details in XML tags."
            },
            {
                "role": "assistant",
                "content": assistant_xml
            }
        ]
    }

    records.append(sample)

output_file = "train.xml.jsonl"

with open(output_file, "w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

print(f"✅ XML-based fine-tuning dataset created: {output_file}")
print(f"Total samples: {len(records)}")

In [ ]:
import json
records = []

for _, row in df.iterrows():
    old_hs = str(row["OldHSCode"]).strip()
    new_hs = str(row["NewHSCode"]).strip()
    desc_en = str(row["LongDescEn"]).strip()

    unit = str(row["StatisticalQtyUnit"]).strip()
    duty = str(row["DutyPercentage"]).strip()
    alt_duty = str(row["AltDutyPercentage"]).strip()
    service = str(row["ServiceCharge"]).strip()
    exemption = str(row["Exemption"]).strip()
    spec_duty = str(row["SpecificDuty"]).strip()
    spec_qty = str(row["SpecificDutyQty"]).strip()

    # --- Assistant output as CLEAN JSON (best for model learning) ----
    assistant_json = {
        "NewHSCode": new_hs,
        "OldHSCode": old_hs,
        "StatisticalQtyUnit": unit,
        "DutyPercentage": duty,
        "AltDutyPercentage": alt_duty,
        "ServiceCharge": service,
        "Exemption": exemption,
        "SpecificDuty": spec_duty,
        "SpecificDutyQty": spec_qty
    }

    sample = {
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are an HS Code classification assistant. "
                    "Always provide the New HS Code clearly and accurately along with related attributes."
                )
            },
            {
                "role": "user",
                "content": f"Item description: {desc_en}. Provide all HS details in JSON format."
            },
            {
                "role": "assistant",
                "content": json.dumps(assistant_json, ensure_ascii=False)
            }
        ]
    }

    records.append(sample)

output_file = "train.jsonl"

with open(output_file, "w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

print(f"✅ Fine-tuning dataset created successfully: {output_file}")
print(f"Total samples: {len(records)}")

✅ Fine-tuning dataset created successfully: train.jsonl
Total samples: 13449

shorted system prompt

In [ ]:
import json
records = []

for _, row in df.iterrows():
    old_hs = str(row["OldHSCode"]).strip()
    new_hs = str(row["NewHSCode"]).strip()
    desc_en = str(row["LongDescEn"]).strip()

    unit = str(row["StatisticalQtyUnit"]).strip()
    duty = str(row["DutyPercentage"]).strip()
    alt_duty = str(row["AltDutyPercentage"]).strip()
    service = str(row["ServiceCharge"]).strip()
    exemption = str(row["Exemption"]).strip()
    spec_duty = str(row["SpecificDuty"]).strip()
    spec_qty = str(row["SpecificDutyQty"]).strip()

    sample = {
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are an HS Code classification assistant. "
                    "Always present the New HS Code first, clearly and accurately."
                )
            },
            {
                "role": "user",
                "content": f"Item description: {desc_en}. Provide full HS details."
            },
            {
                "role": "assistant",
                "content": (
                    f"Here are the complete HS details:\n\n"
                    f"**New HS Code (Primary):** {new_hs}\n"
                    f"**Old HS Code:** {old_hs}\n\n"
                    f"**Statistical Quantity Unit:** {unit}\n"
                    f"**Duty Percentage:** {duty}%\n"
                    f"**Alternate Duty Percentage:** {alt_duty}\n"
                    f"**Service Charge:** {service}\n"
                    f"**Exemption:** {exemption}\n"
                    f"**Specific Duty:** {spec_duty}\n"
                    f"**Specific Duty Quantity:** {spec_qty}\n\n"
                    f"Let me know if you'd like help with another item!"
                )
            }
        ]
    }

    records.append(sample)

output_file = "train.jsonl"

with open(output_file, "w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

print(f"✅ Fine-tuning dataset created successfully: {output_file}")
print(f"Total samples: {len(records)}")

✅ Fine-tuning dataset created successfully: train.jsonl
Total samples: 13449

In [ ]:
with open("/content/hs_finetune_dataset.jsonl", "r") as f:
    for i, line in enumerate(f, 1):
        try:
            import json
            json.loads(line)
        except json.JSONDecodeError:
            print(f"Invalid JSON on line {i}")

# Bilingual dataset

In [ ]:
import pandas as pd
import json

# Create bilingual training pairs
records = []

for _, row in df.iterrows():
    new_hscode = str(row["NewHSCode"]).strip()
    desc_en = str(row["LongDescEn"]).strip()
    desc_ar = str(row["LongDescAr"]).strip()
    unit = str(row["StatisticalQtyUnit"]).strip()
    duty = str(row["DutyPercentage"]).strip()
    alt_duty = str(row["AltDutyPercentage"]).strip()

    # ---- English version ----
    user_en = {
        "role": "user",
        "content": f"What is the HS Code for {desc_en}?"
    }
    assistant_en = {
        "role": "assistant",
        "content": (
            f"HS Code -> {new_hscode}\n"
            f"Reasoning -> The item '{desc_en}' is classified under HS Code {new_hscode} "
            f"based on its description and category. "
            f"Duty: {duty}%, Alt Duty: {alt_duty}%, Unit: {unit}."
        )
    }
    records.append([user_en, assistant_en])

    # ---- Arabic version ----
    user_ar = {
        "role": "user",
        "content": f"ما هو رمز النظام المنسق (HS Code) لـ{desc_ar}؟"
    }
    assistant_ar = {
        "role": "assistant",
        "content": (
            f"رمز النظام المنسق -> {new_hscode}\n"
            f"السبب -> يُصنف البند '{desc_ar}' تحت رمز النظام المنسق {new_hscode} "
            f"وفقًا لوصفه وفئته. الرسوم الجمركية: {duty}٪، الرسوم البديلة: {alt_duty}٪، وحدة القياس: {unit}."
        )
    }
    records.append([user_ar, assistant_ar])

# Save as JSON
output_file = "bilingual_finetune_dataset.json"
with open(output_file, "w", encoding="utf-8") as f:
    json.dump(records, f, ensure_ascii=False, indent=2)

print(f"✅ Bilingual fine-tuning dataset created successfully: {output_file}")
print(f"Total samples: {len(records)}")

✅ Bilingual fine-tuning dataset created successfully: bilingual_finetune_dataset.json
Total samples: 26898

# (OR)

In [ ]:
import pandas as pd
import json

with open("llama31_finetune_dataset.jsonl", "w", encoding="utf-8") as f:
    for _, row in df.iterrows():
        new_hscode = str(row["NewHSCode"]).strip()
        desc_en = str(row["LongDescEn"]).strip()
        desc_ar = str(row["LongDescAr"]).strip()
        unit = str(row["StatisticalQtyUnit"]).strip()
        duty = str(row["DutyPercentage"]).strip()
        alt_duty = str(row["AltDutyPercentage"]).strip()

        # English sample
        convo_en = {
            "messages": [
                {"role": "user", "content": f"What is the HS Code for {desc_en}?"},
                {"role": "assistant", "content": (
                    f"HS Code -> {new_hscode}\n"
                    f"Reasoning -> The item '{desc_en}' is classified under HS Code {new_hscode}. "
                    f"Duty: {duty}%, Alt Duty: {alt_duty}%, Unit: {unit}."
                )}
            ]
        }
        f.write(json.dumps(convo_en, ensure_ascii=False) + "\n")

        # Arabic sample
        convo_ar = {
            "messages": [
                {"role": "user", "content": f"ما هو رمز النظام المنسق (HS Code) لـ{desc_ar}؟"},
                {"role": "assistant", "content": (
                    f"رمز النظام المنسق -> {new_hscode}\n"
                    f"السبب -> يُصنف البند '{desc_ar}' تحت رمز النظام المنسق {new_hscode}. "
                    f"الرسوم الجمركية: {duty}٪، الرسوم البديلة: {alt_duty}٪، وحدة القياس: {unit}."
                )}
            ]
        }
        f.write(json.dumps(convo_ar, ensure_ascii=False) + "\n")

print("✅ Saved dataset in JSONL format for LLaMA 3.1 fine-tuning.")

✅ Saved dataset in JSONL format for LLaMA 3.1 fine-tuning.

# Final one: Both bilingual datas in the same row

In [ ]:
import pandas as pd
import json

with open("bilingual_llama31_finetune_dataset.jsonl", "w", encoding="utf-8") as f:
    for _, row in df.iterrows():
        new_hscode = str(row["NewHSCode"]).strip()
        desc_en = str(row["LongDescEn"]).strip()
        desc_ar = str(row["LongDescAr"]).strip()
        unit = str(row["StatisticalQtyUnit"]).strip()
        duty = str(row["DutyPercentage"]).strip()
        alt_duty = str(row["AltDutyPercentage"]).strip()

        convo = {
            "messages": [
                {
                    "role": "user",
                    "content":
                        (
                            "You are an expert HS Code classification system.\n\n"
                            f"English description: {desc_en}\n"
                            f"Arabic description: {desc_ar}\n\n"
                            "Provide the correct HS Code and a short reasoning. "
                            "Include Duty, Alt Duty, and Statistical Unit."
                        )
                },
                {
                    "role": "assistant",
                    "content":
                        (
                            f"HS Code: {new_hscode}\n"
                            f"Reasoning: The item is classified under HS Code {new_hscode}.\n"
                            f"Duty: {duty}%\n"
                            f"Alt Duty: {alt_duty}%\n"
                            f"Unit: {unit}"
                        )
                }
            ]
        }

        f.write(json.dumps(convo, ensure_ascii=False) + "\n")

print("✅ Created bilingual LLaMA 3.1 training dataset (English + Arabic combined).")

In [ ]:
import json

path = "/content/drive/MyDrive/Finetuning_Llama_3.1/bilingual_llama31_finetune_dataset.jsonl"

with open(path, "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        if i < 5:  # show first 5 lines
            data = json.loads(line)
            print(json.dumps(data, indent=2, ensure_ascii=False))

{
  "messages": [
    {
      "role": "user",
      "content": "You are an expert HS Code classification system.\n\nEnglish description: Live pure-bred breeding  horses of Arabian  breed - Of Arab breed males\nArabic description: خيول اصيلة الانسال من اصل عربي   - ذكور خيول من اصل عربي للأنسال\n\nProvide the correct HS Code and a short reasoning. Include Duty, Alt Duty, and Statistical Unit."
    },
    {
      "role": "assistant",
      "content": "HS Code: 10121100001\nReasoning: The item is classified under HS Code 10121100001.\nDuty: 0%\nAlt Duty: 0%\nUnit: Kilograms"
    }
  ]
}
{
  "messages": [
    {
      "role": "user",
      "content": "You are an expert HS Code classification system.\n\nEnglish description: Live pure-bred breeding  horses of Arabian  breed - Of Arab breed females\nArabic description: خيول اصيلة الانسال من اصل عربي   - إناث خيول من أصل عربي للأنسال\n\nProvide the correct HS Code and a short reasoning. Include Duty, Alt Duty, and Statistical Unit."
    },
    {
      "role": "assistant",
      "content": "HS Code: 10121100002\nReasoning: The item is classified under HS Code 10121100002.\nDuty: 0%\nAlt Duty: 0%\nUnit: Kilograms"
    }
  ]
}
{
  "messages": [
    {
      "role": "user",
      "content": "You are an expert HS Code classification system.\n\nEnglish description: Other live pure-bred breeding horses other than of Arabian breed. - Of non-Arab breed males\nArabic description: خيول اصيلة الانسال ما عدا  الخيول التي من اصل عربي   - ذكور خيول من أصل غير عربي للأنسال\n\nProvide the correct HS Code and a short reasoning. Include Duty, Alt Duty, and Statistical Unit."
    },
    {
      "role": "assistant",
      "content": "HS Code: 10121900001\nReasoning: The item is classified under HS Code 10121900001.\nDuty: 0%\nAlt Duty: 0%\nUnit: Pieces/Units"
    }
  ]
}
{
  "messages": [
    {
      "role": "user",
      "content": "You are an expert HS Code classification system.\n\nEnglish description: Other live pure-bred breeding horses other than of Arabian breed. - Of non-Arab breed females\nArabic description: خيول اصيلة الانسال ما عدا  الخيول التي من اصل عربي   - إناث خيول من أصل غير عربي للأنسال\n\nProvide the correct HS Code and a short reasoning. Include Duty, Alt Duty, and Statistical Unit."
    },
    {
      "role": "assistant",
      "content": "HS Code: 10121900002\nReasoning: The item is classified under HS Code 10121900002.\nDuty: 0%\nAlt Duty: 0%\nUnit: Pieces/Units"
    }
  ]
}
{
  "messages": [
    {
      "role": "user",
      "content": "You are an expert HS Code classification system.\n\nEnglish description: Live sport horses other than pur- bred breeding animals - Males of Arab breed for sport\nArabic description: خيول رياضه من أصل غير عربي للرياضة\n\nProvide the correct HS Code and a short reasoning. Include Duty, Alt Duty, and Statistical Unit."
    },
    {
      "role": "assistant",
      "content": "HS Code: 10129100001\nReasoning: The item is classified under HS Code 10129100001.\nDuty: 0%\nAlt Duty: 0%\nUnit: Pieces/Units"
    }
  ]
}

# Only english

In [ ]:
import pandas as pd
import json

# Save only English samples
with open("en_llama31_finetune_dataset.jsonl", "w", encoding="utf-8") as f:
    for _, row in df.iterrows():
        new_hscode = str(row["NewHSCode"]).strip()
        desc_en = str(row["LongDescEn"]).strip()
        unit = str(row["StatisticalQtyUnit"]).strip()
        duty = str(row["DutyPercentage"]).strip()
        alt_duty = str(row["AltDutyPercentage"]).strip()

        # English sample only
        convo_en = {
            "messages": [
                {"role": "user", "content": f"What is the HS Code for {desc_en}?"},
                {"role": "assistant", "content": (
                    f"HS Code -> {new_hscode}\n"
                    f"Reasoning -> The item '{desc_en}' is classified under HS Code {new_hscode}. "
                    f"Duty: {duty}%, Alt Duty: {alt_duty}%, Unit: {unit}."
                )}
            ]
        }
        f.write(json.dumps(convo_en, ensure_ascii=False) + "\n")

print("✅ Saved English-only dataset in JSONL format for LLaMA 3.1 fine-tuning.")

✅ Saved English-only dataset in JSONL format for LLaMA 3.1 fine-tuning.