In [ ]:
!pip install pandas langchain faiss-cpu sentence-transformers

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.3.3)
Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.0)
Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.13.1)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.2.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.1)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.0.5)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (25.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.57.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.9.0+cpu)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (0.36.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.2.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.4.59)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (9.1.2)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.12.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.5)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.3.0)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.1->langchain) (3.0.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.1)
Requirement already satisfied: httpx>=0.25.2 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.1->langchain) (0.25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.11.12)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (4.12.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.2->langchain) (0.16.0)

# CSV → Vector DB (semantic) → HS Object → TOON Prompt → Chatbot Response

In [ ]:
import pandas as pd

df = pd.read_excel("/content/drive/MyDrive/HS_Code_Rag/HSCodeMaster v3.2.xlsx", dtype=str)
pd.set_option('display.max_colwidth', None)
df.head()

,OldHSCode,NewHSCode,LongDescAr,LongDescEn,Unit,Consignment,StatisticalQtyUnit,IS_Vehicle,CDM_Priority,DutyPercentage,AltDutyPercentage,ServiceCharge,Exemption,SpecificDuty,SpecificDutyQty,VGNMat
0,01012110,010121100001,خيول اصيلة الانسال من اصل عربي - ذكور خيول من اصل عربي للأنسال,Live pure-bred breeding horses of Arabian breed - Of Arab breed males,القيمةVALUE,Normal,Kilograms,No,Medium,0,0,0,NaN,NaN,NaN,New Sub
1,01012110,010121100002,خيول اصيلة الانسال من اصل عربي - إناث خيول من أصل عربي للأنسال,Live pure-bred breeding horses of Arabian breed - Of Arab breed females,القيمةVALUE,Normal,Kilograms,No,Medium,0,0,0,NaN,NaN,NaN,New Sub
2,01012190,010121900001,خيول اصيلة الانسال ما عدا الخيول التي من اصل عربي - ذكور خيول من أصل غير عربي للأنسال,Other live pure-bred breeding horses other than of Arabian breed. - Of non-Arab breed males,القيمةVALUE,Normal,Pieces/Units,No,Medium,0,0,0,NaN,NaN,NaN,New Sub
3,01012190,010121900002,خيول اصيلة الانسال ما عدا الخيول التي من اصل عربي - إناث خيول من أصل غير عربي للأنسال,Other live pure-bred breeding horses other than of Arabian breed. - Of non-Arab breed females,القيمةVALUE,Normal,Pieces/Units,No,Medium,0,0,0,NaN,NaN,NaN,New Sub
4,01012910,010129100001,خيول رياضه من أصل غير عربي للرياضة,Live sport horses other than pur- bred breeding animals - Males of Arab breed for sport,القيمةVALUE,Normal,Pieces/Units,No,Medium,0,0,0,NaN,NaN,NaN,New Sub

In [ ]:
df.drop(["Unit","Consignment","IS_Vehicle","CDM_Priority","VGNMat"], axis = 1, inplace = True)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#df.drop(["OldHSCode"], axis = 1, inplace = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13449 entries, 0 to 13448
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   OldHSCode           13449 non-null  object
 1   NewHSCode           13449 non-null  object
 2   LongDescAr          13449 non-null  object
 3   LongDescEn          13449 non-null  object
 4   StatisticalQtyUnit  13449 non-null  object
 5   DutyPercentage      13449 non-null  object
 6   AltDutyPercentage   13449 non-null  object
 7   ServiceCharge       13449 non-null  object
 8   Exemption           7106 non-null   object
 9   SpecificDuty        11074 non-null  object
 10  SpecificDutyQty     10834 non-null  object
dtypes: object(11)
memory usage: 1.1+ MB

In [ ]:
df = df.fillna("0")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13449 entries, 0 to 13448
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   OldHSCode           13449 non-null  object
 1   NewHSCode           13449 non-null  object
 2   LongDescAr          13449 non-null  object
 3   LongDescEn          13449 non-null  object
 4   StatisticalQtyUnit  13449 non-null  object
 5   DutyPercentage      13449 non-null  object
 6   AltDutyPercentage   13449 non-null  object
 7   ServiceCharge       13449 non-null  object
 8   Exemption           13449 non-null  object
 9   SpecificDuty        13449 non-null  object
 10  SpecificDutyQty     13449 non-null  object
dtypes: object(11)
memory usage: 1.1+ MB

In [ ]:
df.rename(columns={'NewHSCode': 'final_hs_code'}, inplace=True)

In [ ]:
import re

def normalize_text(text):
    if not isinstance(text, str):
        return ""

    text = text.lower()
    text = re.sub(r"[-–—]", " ", text)   # normalize hyphens/dashes
    text = re.sub(r"\.", " ", text)       # remove dots
    text = re.sub(r"\s+", " ", text)     # collapse multiple spaces
    return text.strip()

In [ ]:
df["LongDescEn"] = df["LongDescEn"].apply(normalize_text)

In [ ]:
df["LongDescEn"].head()

0                           live pure bred breeding horses of arabian breed of arab breed males
1                         live pure bred breeding horses of arabian breed of arab breed females
2      other live pure bred breeding horses other than of arabian breed of non arab breed males
3    other live pure bred breeding horses other than of arabian breed of non arab breed females
4          live sport horses other than pur bred breeding animals males of arab breed for sport
Name: LongDescEn, dtype: object

In [ ]:
import re

def normalize_arabic_text(text):
    if not isinstance(text, str):
        return ""

    # Normalize Arabic letters
    text = re.sub("[إأآا]", "ا", text)
    text = re.sub("ى", "ي", text)
    text = re.sub("ؤ", "و", text)
    text = re.sub("ئ", "ي", text)
    text = re.sub("ة", "ه", text)

    # Remove tashkeel (diacritics)
    text = re.sub(r"[\u064B-\u0652]", "", text)

    # Remove punctuation and symbols
    text = re.sub(r"[^\u0600-\u06FF\s]", " ", text)

    # Normalize spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [ ]:
df["LongDescAr"] = df["LongDescAr"].apply(normalize_arabic_text)

In [ ]:
df["LongDescAr"].head()

0                           خيول اصيله الانسال من اصل عربي ذكور خيول من اصل عربي للانسال
1                           خيول اصيله الانسال من اصل عربي اناث خيول من اصل عربي للانسال
2    خيول اصيله الانسال ما عدا الخيول التي من اصل عربي ذكور خيول من اصل غير عربي للانسال
3    خيول اصيله الانسال ما عدا الخيول التي من اصل عربي اناث خيول من اصل غير عربي للانسال
4                                                     خيول رياضه من اصل غير عربي للرياضه
Name: LongDescAr, dtype: object

In [ ]:
#df.to_csv("/content/drive/MyDrive/HS_Code_Rag/hs_code_processed_ar_en.csv", index=False)

# Converting Each Row → Document

In [ ]:
from langchain_core.documents import Document


documents = []



for _, row in df.iterrows():

    metadata = {
        "FinalHSCode": row["final_hs_code"],
        "OldHSCode": row["OldHSCode"],
        "StatisticalQtyUnit": row["StatisticalQtyUnit"],
        "DutyPercentage": row["DutyPercentage"],
        "AltDutyPercentage": row["AltDutyPercentage"],
        "ServiceCharge": row["ServiceCharge"],
        "Exemption": row["Exemption"],
        "SpecificDuty": row["SpecificDuty"],
        "SpecificDutyQty": row["SpecificDutyQty"],
    }

    # English document
    documents.append(
        Document(
            page_content=f"Product description: {row['LongDescEn']}",
            metadata={**metadata, "lang": "en"}
        )
    )

    # Arabic document
    documents.append(
        Document(
            page_content=f"Product description: {row['LongDescAr']}",
            metadata={**metadata, "lang": "ar"}
        )
    )

In [ ]:
for doc in documents[:10]:
    print(doc)
    print("-" * 80)

page_content='Product description: live pure bred breeding horses of arabian breed of arab breed males' metadata={'FinalHSCode': '010121100001', 'OldHSCode': '01012110', 'StatisticalQtyUnit': 'Kilograms', 'DutyPercentage': '0', 'AltDutyPercentage': '0', 'ServiceCharge': '0', 'Exemption': '0', 'SpecificDuty': '0', 'SpecificDutyQty': '0', 'lang': 'en'}
--------------------------------------------------------------------------------
page_content='Product description: خيول اصيله الانسال من اصل عربي ذكور خيول من اصل عربي للانسال' metadata={'FinalHSCode': '010121100001', 'OldHSCode': '01012110', 'StatisticalQtyUnit': 'Kilograms', 'DutyPercentage': '0', 'AltDutyPercentage': '0', 'ServiceCharge': '0', 'Exemption': '0', 'SpecificDuty': '0', 'SpecificDutyQty': '0', 'lang': 'ar'}
--------------------------------------------------------------------------------
page_content='Product description: live pure bred breeding horses of arabian breed of arab breed females' metadata={'FinalHSCode': '010121100002', 'OldHSCode': '01012110', 'StatisticalQtyUnit': 'Kilograms', 'DutyPercentage': '0', 'AltDutyPercentage': '0', 'ServiceCharge': '0', 'Exemption': '0', 'SpecificDuty': '0', 'SpecificDutyQty': '0', 'lang': 'en'}
--------------------------------------------------------------------------------
page_content='Product description: خيول اصيله الانسال من اصل عربي اناث خيول من اصل عربي للانسال' metadata={'FinalHSCode': '010121100002', 'OldHSCode': '01012110', 'StatisticalQtyUnit': 'Kilograms', 'DutyPercentage': '0', 'AltDutyPercentage': '0', 'ServiceCharge': '0', 'Exemption': '0', 'SpecificDuty': '0', 'SpecificDutyQty': '0', 'lang': 'ar'}
--------------------------------------------------------------------------------
page_content='Product description: other live pure bred breeding horses other than of arabian breed of non arab breed males' metadata={'FinalHSCode': '010121900001', 'OldHSCode': '01012190', 'StatisticalQtyUnit': 'Pieces/Units', 'DutyPercentage': '0', 'AltDutyPercentage': '0', 'ServiceCharge': '0', 'Exemption': '0', 'SpecificDuty': '0', 'SpecificDutyQty': '0', 'lang': 'en'}
--------------------------------------------------------------------------------
page_content='Product description: خيول اصيله الانسال ما عدا الخيول التي من اصل عربي ذكور خيول من اصل غير عربي للانسال' metadata={'FinalHSCode': '010121900001', 'OldHSCode': '01012190', 'StatisticalQtyUnit': 'Pieces/Units', 'DutyPercentage': '0', 'AltDutyPercentage': '0', 'ServiceCharge': '0', 'Exemption': '0', 'SpecificDuty': '0', 'SpecificDutyQty': '0', 'lang': 'ar'}
--------------------------------------------------------------------------------
page_content='Product description: other live pure bred breeding horses other than of arabian breed of non arab breed females' metadata={'FinalHSCode': '010121900002', 'OldHSCode': '01012190', 'StatisticalQtyUnit': 'Pieces/Units', 'DutyPercentage': '0', 'AltDutyPercentage': '0', 'ServiceCharge': '0', 'Exemption': '0', 'SpecificDuty': '0', 'SpecificDutyQty': '0', 'lang': 'en'}
--------------------------------------------------------------------------------
page_content='Product description: خيول اصيله الانسال ما عدا الخيول التي من اصل عربي اناث خيول من اصل غير عربي للانسال' metadata={'FinalHSCode': '010121900002', 'OldHSCode': '01012190', 'StatisticalQtyUnit': 'Pieces/Units', 'DutyPercentage': '0', 'AltDutyPercentage': '0', 'ServiceCharge': '0', 'Exemption': '0', 'SpecificDuty': '0', 'SpecificDutyQty': '0', 'lang': 'ar'}
--------------------------------------------------------------------------------
page_content='Product description: live sport horses other than pur bred breeding animals males of arab breed for sport' metadata={'FinalHSCode': '010129100001', 'OldHSCode': '01012910', 'StatisticalQtyUnit': 'Pieces/Units', 'DutyPercentage': '0', 'AltDutyPercentage': '0', 'ServiceCharge': '0', 'Exemption': '0', 'SpecificDuty': '0', 'SpecificDutyQty': '0', 'lang': 'en'}
--------------------------------------------------------------------------------
page_content='Product description: خيول رياضه من اصل غير عربي للرياضه' metadata={'FinalHSCode': '010129100001', 'OldHSCode': '01012910', 'StatisticalQtyUnit': 'Pieces/Units', 'DutyPercentage': '0', 'AltDutyPercentage': '0', 'ServiceCharge': '0', 'Exemption': '0', 'SpecificDuty': '0', 'SpecificDutyQty': '0', 'lang': 'ar'}
--------------------------------------------------------------------------------

In [ ]:
pip install -U langchain langchain-community

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.0)
Requirement already satisfied: langchain-community in /usr/local/lib/python3.12/dist-packages (0.4.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.1)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.0.5)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.0.0)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.45)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.13.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.2)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.12.0)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.59)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community) (1.1.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (1.33)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (25.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.12.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.5)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.3.0)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2025.11.12)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.3.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (4.12.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.1->langchain) (3.0.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community) (1.1.0)

**Creating Embeddings**

In [ ]:
from langchain_community.embeddings import HuggingFaceEmbeddings

# Load local embeddings model
embedding_model = HuggingFaceEmbeddings(model_name="omarelshehy/arabic-english-sts-matryoshka-v2.0")

/tmp/ipython-input-1070318103.py:4: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  embedding_model = HuggingFaceEmbeddings(model_name="omarelshehy/arabic-english-sts-matryoshka-v2.0")
WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

# Building vector store

In [ ]:
"""from langchain_community.vectorstores import FAISS
FAISS_PATH = "/content/drive/MyDrive/HS_Code_Rag/faiss_hscode_index_ar_en"

vectorstore = FAISS.from_documents(
    documents=documents,
    embedding=embedding_model
)
vectorstore.save_local(FAISS_PATH)"""

'from langchain_community.vectorstores import FAISS\nFAISS_PATH = "/content/drive/MyDrive/HS_Rag/faiss_hscode_index_ar_en"\n\nvectorstore = FAISS.from_documents(\n    documents=documents,\n    embedding=embedding_model\n)\nvectorstore.save_local(FAISS_PATH)'

**Creating retriever**

In [ ]:
from langchain_community.vectorstores import FAISS

# Loading saved vectorstore
FAISS_PATH = "/content/drive/MyDrive/HS_Code_Rag/faiss_hscode_index_ar_en"
vectorstore = FAISS.load_local(
    FAISS_PATH,
    embedding_model,
    allow_dangerous_deserialization=True
)

**TOON Format**

In [ ]:
def format_context_toon(docs):
    if not isinstance(docs, list):
        docs = [docs]

    fields = [

        "final_hs_code",
        "description",
        "duty_fee",
        #"OldHSCode",
        #"statistical_qty_unit",
        # "alternate_duty_percent",
        # "service_charge",
        # "exemption",
        # "specific_duty",
        # "specific_duty_qty",
    ]

    header = f"hs_records[{len(docs)}]{{{','.join(fields)}}}:"

    rows = []
    for doc in docs:
        row = [

            doc.metadata.get("FinalHSCode"),
            doc.page_content.replace("Product description:", "").strip(),
            doc.metadata.get("DutyPercentage"),
            #doc.metadata.get("OldHSCode"),
            #doc.metadata.get("StatisticalQtyUnit"),
            # doc.metadata.get("AltDutyPercentage"),
            # doc.metadata.get("ServiceCharge"),
            # doc.metadata.get("Exemption"),
            # doc.metadata.get("SpecificDuty"),
            # doc.metadata.get("SpecificDutyQty"),
        ]
        rows.append(",".join("" if v is None else str(v) for v in row))


    return header + "\n" + "\n".join(rows)

In [ ]:
TOON_PROMPT = """
You are a customs declaration verifier.
You are given one authoritative HS record as JSON.
Verify the incoming declaration against the HS record and report each field separately:

HS code:
- If it matches, say: Declaration HS code is correct.
- If not, say: For this description, the declared HS code is incorrect.
  Then provide the correct HS code from the HS record.
- Never use or mention old_hs_code in the response.

Description:
- If it matches, say: Declaration description is matching.

Duty fee:
- If it matches, say: Declaration duty fee is correct.
- If not, say: The declared duty fee is incorrect.
  Then provide the correct duty value from the HS record.

Risk rule:
- If HS code, description, and duty fee are all correct → "The declaration is non risky."
- Otherwise → "The declaration is risky."


Rules:
- Do NOT infer missing data or add explanations.
- Do NOT modify numeric values.
- If a value is not present in the HS record, say: Not available in the HS dataset.
- Output only the verification results.

HS_RECORD:
{hs_record}

INCOMING_DECLARATION:
{incoming_declaration}

OUTPUT RESPONSE (use this exact format):

Risk: <result>
HS code: <result>
Description: <result>
Duty fee: <result>
"""

In [ ]:
import requests

OLLAMA_URL = "http://185.216.21.192:11434/api/generate"
MODEL_NAME = "llama3.1:8b"

def llm(prompt: str) -> str:
    response = requests.post(
        OLLAMA_URL,
        json={
            "model": MODEL_NAME,
            "prompt": prompt,
            "stream": False
        },
        timeout=120
    )

    response.raise_for_status()
    return response.json()["response"]

In [ ]:
hs_codes_set = set(df['final_hs_code'].unique())

def verify_hs_code(hs_code):
    return hs_code in hs_codes_set

def detect_language(text):
    return "ar" if re.search(r"[\u0600-\u06FF]", text) else "en"

In [ ]:
import json
def hscode_verification_toon(incoming_declaration):

    # STEP 1: Get raw description
    query = incoming_declaration.get("description", "")

    # STEP 2: Detect language
    lang = detect_language(query)
    print("language:", lang)

    # STEP 3: Normalize based on language
    if lang == "ar":
        cleaned_query = normalize_arabic_text(query)
    else:
        cleaned_query = normalize_text(query)

    # STEP 4: Update declaration with cleaned description
    incoming_declaration["description"] = cleaned_query


    retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 3,
        "filter": {"lang": lang}
    })

    # STEP 5: Retrieval using cleaned description
    result = retriever.invoke(cleaned_query)

    if not result:
        return "No matching HS code found for the given description."

    docs = result if isinstance(result, list) else [result]

    hs_record = format_context_toon(docs)

    # STEP 6: Prompt
    prompt = TOON_PROMPT.format(
        hs_record=json.dumps(hs_record, indent=2),
        incoming_declaration=incoming_declaration
    )

    #print("PROMPT---")
    #print(prompt)

    return llm(prompt)

In [ ]:
from IPython.display import HTML, display


# MAIN EXECUTION FLOW

incoming_declaration = {
    "hs_code": "010121100002",
    "description": "Live pure-bred breeding  horses of Arabian  breed - Of Arab breed females",
    "duty_fee": "0",
}

#incoming_description = normalize_text(incoming_declaration["description"])

# STEP 1: HS code verification
hs_code = verify_hs_code(incoming_declaration.get("hs_code"))
print(hs_code)

if hs_code:
    # STEP 2: Continue RAG pipeline only if HS code is valid
    response = hscode_verification_toon(incoming_declaration)
else:
    response = "Invalid HS Code. Not available in the HS dataset."

# STEP 3: Display response
display(
    HTML(
        f"<div style='white-space: pre-wrap; "
        f"max-width: 100%; "
        f"font-family: monospace; "
        f"font-size: 14px;'>"
        f"{response}"
        f"</div>"
    )
)

True
language: en

In [ ]:
from IPython.display import HTML, display


# MAIN EXECUTION FLOW

incoming_declaration = {
    "hs_code": "010121900001",
    "description": "خيول رياضه ما عدا  الخيول التي من اصل عربي   - إناث خيول من أصل عربي للرياضة",
    "duty_fee": "5",
}

#incoming_description = normalize_text(incoming_declaration["description"])

# STEP 1: HS code verification
hs_code = verify_hs_code(incoming_declaration.get("hs_code"))
print(hs_code)

if hs_code:
    # STEP 2: Continue RAG pipeline only if HS code is valid
    response = hscode_verification_toon(incoming_declaration)
else:
    response = "Invalid HS Code. Not available in the HS dataset."

# STEP 3: Display response
display(
    HTML(
        f"<div style='white-space: pre-wrap; "
        f"max-width: 100%; "
        f"font-family: monospace; "
        f"font-size: 14px;'>"
        f"{response}"
        f"</div>"
    )
)

True
language: ar

**Streamlit Part**

In [ ]:
!pip install -U langchain langchain-community pandas langchain faiss-cpu sentence-transformers streamlit pyngrok

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.0)
Collecting langchain-community
  Downloading langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting pandas
  Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 1.4 MB/s eta 0:00:00
Collecting faiss-cpu
  Downloading faiss_cpu-1.13.1-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.6 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.2.0)
Collecting streamlit
  Downloading streamlit-1.52.2-py3-none-any.whl.metadata (9.8 kB)
Collecting pyngrok
  Downloading pyngrok-7.5.0-py3-none-any.whl.metadata (8.1 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.1)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.0.5)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain-community)
  Downloading langchain_classic-1.0.0-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.45)
Collecting requests<3.0.0,>=2.32.5 (from langchain-community)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.13.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.2)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.12.0)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.59)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (25.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.57.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.9.0+cpu)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (0.36.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.4)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.5)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.45)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.25.1)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.13.0)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.2.0)
Collecting langchain-text-splitters<2.0.0,>=1.0.0 (from langchain-classic<2.0.0,>=1.0.0->langchain-community)
  Downloading langchain_text_splitters-1.1.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (1.33)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.1->langchain) (0.12.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.5)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.3.0)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.5)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2025.11.12)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.3.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (4.12.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.1->langchain) (3.0.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Collecting mypy-extensions>=0.3.0 (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Downloading langchain_community-0.4.1-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 19.9 MB/s eta 0:00:00
Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 23.8 MB/s eta 0:00:00
Downloading faiss_cpu-1.13.1-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (23.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 23.6 MB/s eta 0:00:00
Downloading streamlit-1.52.2-py3-none-any.whl (9.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.0/9.0 MB 29.5 MB/s eta 0:00:00
Downloading pyngrok-7.5.0-py3-none-any.whl (24 kB)
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading langchain_classic-1.0.0-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 17.6 MB/s eta 0:00:00
Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 28.3 MB/s eta 0:00:00
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 2.1 MB/s eta 0:00:00
Downloading langchain_text_splitters-1.1.0-py3-none-any.whl (34 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 1.5 MB/s eta 0:00:00
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Installing collected packages: requests, pyngrok, mypy-extensions, marshmallow, faiss-cpu, typing-inspect, pydeck, pandas, dataclasses-json, streamlit, langchain-text-splitters, langchain-classic, langchain-community
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.32.5 which is incompatible.
Successfully installed dataclasses-json-0.6.7 faiss-cpu-1.13.1 langchain-classic-1.0.0 langchain-community-0.4.1 langchain-text-splitters-1.1.0 marshmallow-3.26.2 mypy-extensions-1.1.0 pandas-2.3.3 pydeck-0.9.1 pyngrok-7.5.0 requests-2.32.5 streamlit-1.52.2 typing-inspect-0.9.0

In [ ]:
%%writefile app.py
import streamlit as st
from IPython.display import HTML
import pandas as pd
import re
import requests
import json
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings


df = pd.read_csv("/content/drive/MyDrive/HS_Code_Rag/hs_code_processed_ar_en.csv", dtype=str)

hs_codes_set = set(df['final_hs_code'].unique())

def verify_hs_code(hs_code):
    return hs_code in hs_codes_set

def detect_language(text):
    return "ar" if re.search(r"[\u0600-\u06FF]", text) else "en"

def normalize_text(text):
    if not isinstance(text, str):
        return ""

    text = text.lower()
    text = re.sub(r"[-–—]", " ", text)   # normalize hyphens/dashes
    text = re.sub(r"\.", " ", text)       # remove dots
    text = re.sub(r"\s+", " ", text)     # collapse multiple spaces
    return text.strip()

def normalize_arabic_text(text):
    if not isinstance(text, str):
        return ""

    # Normalize Arabic letters
    text = re.sub("[إأآا]", "ا", text)
    text = re.sub("ى", "ي", text)
    text = re.sub("ؤ", "و", text)
    text = re.sub("ئ", "ي", text)
    text = re.sub("ة", "ه", text)

    # Remove tashkeel (diacritics)
    text = re.sub(r"[\u064B-\u0652]", "", text)

    # Remove punctuation and symbols
    text = re.sub(r"[^\u0600-\u06FF\s]", " ", text)

    # Normalize spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip()


# Load local embeddings model
embedding_model = HuggingFaceEmbeddings(model_name="omarelshehy/arabic-english-sts-matryoshka-v2.0")


# Loading saved vectorstore
FAISS_PATH = "/content/drive/MyDrive/HS_Code_Rag/faiss_hscode_index_ar_en"
vectorstore = FAISS.load_local(
    FAISS_PATH,
    embedding_model,
    allow_dangerous_deserialization=True
)


def hscode_verification_toon(incoming_declaration):

    # STEP 1: Get raw description
    query = incoming_declaration.get("description", "")

    # STEP 2: Detect language
    lang = detect_language(query)
    print("language:", lang)

    # STEP 3: Normalize based on language
    if lang == "ar":
        cleaned_query = normalize_arabic_text(query)
    else:
        cleaned_query = normalize_text(query)

    # STEP 4: Update declaration with cleaned description
    incoming_declaration["description"] = cleaned_query


    retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={
        "k": 3,
        "filter": {"lang": lang}
    })

    # STEP 5: Retrieval using cleaned description
    result = retriever.invoke(cleaned_query)

    if not result:
        return "No matching HS code found for the given description."

    docs = result if isinstance(result, list) else [result]

    hs_record = format_context_toon(docs)

    # STEP 6: Prompt
    prompt = TOON_PROMPT.format(
        hs_record=json.dumps(hs_record, indent=2),
        incoming_declaration=incoming_declaration
    )

    print("PROMPT---")
    print(prompt)

    return llm(prompt)


def format_context_toon(docs):
    if not isinstance(docs, list):
        docs = [docs]

    fields = [

        "final_hs_code",
        #"OldHSCode",
        "description",
        "statistical_qty_unit",
        "duty_fee",
        # "alternate_duty_percent",
        # "service_charge",
        # "exemption",
        # "specific_duty",
        # "specific_duty_qty",
    ]

    header = f"hs_records[{len(docs)}]{{{','.join(fields)}}}:"

    rows = []
    for doc in docs:
        row = [

            doc.metadata.get("FinalHSCode"),
            #doc.metadata.get("OldHSCode"),
            doc.page_content.replace("Product description:", "").strip(),
            doc.metadata.get("StatisticalQtyUnit"),
            doc.metadata.get("DutyPercentage"),
            # doc.metadata.get("AltDutyPercentage"),
            # doc.metadata.get("ServiceCharge"),
            # doc.metadata.get("Exemption"),
            # doc.metadata.get("SpecificDuty"),
            # doc.metadata.get("SpecificDutyQty"),
        ]
        rows.append(",".join("" if v is None else str(v) for v in row))

    return header + "\n" + "\n".join(rows)


TOON_PROMPT = """
You are a customs declaration verifier.
You are given one authoritative HS record as JSON.
Verify the incoming declaration against the HS record and report each field separately:

HS code:
- If it matches, say: Declaration HS code is correct.
- If not, say: For this description, the declared HS code is incorrect.
  Then provide the correct HS code from the HS record.
- Never use or mention old_hs_code in the response.

Description:
- If it matches, say: Declaration description is matching.

Duty fee:
- If it matches, say: Declaration duty fee is correct.
- If not, say: The declared duty fee is incorrect.
  Then provide the correct duty fee from the HS record.

Risk rule:
- If HS code, description, and duty fee are all correct → "The declaration is non risky."
- Otherwise → "The declaration is risky."

Rules:
- Do NOT infer missing data or add explanations.
- Do NOT modify numeric values.
- If a value is not present in the HS record, say: Not available in the HS dataset.
- Output only the verification results.

HS_RECORD:
{hs_record}

INCOMING_DECLARATION:
{incoming_declaration}

OUTPUT RESPONSE (use this exact format):
Here are the verification results:
Risk: <result>
HS code: <result>
Description: <result>
Duty fee: <result>
"""




OLLAMA_URL = "http://185.216.21.192:11434/api/generate"
MODEL_NAME = "llama3.1:8b"

def llm(prompt: str) -> str:
    response = requests.post(
        OLLAMA_URL,
        json={
            "model": MODEL_NAME,
            "prompt": prompt,
            "stream": False
        },
        timeout=120
    )

    response.raise_for_status()
    return response.json()["response"]


# Streamlit Page Config
st.set_page_config(
    page_title="HS Code Declaration Verifier"
    #layout="wide"
)

st.title("Customs Declaration Verification")
st.caption("HS Code | Description | Duty Fee Verification (Arabic & English)")

# User Inputs
with st.form("declaration_form"):
    hs_code = st.text_input(
        "HS Code",
        placeholder="e.g. 010121900001"
    )

    description = st.text_area(
        "Goods Description (Arabic / English)",
        height=120,
        placeholder="Enter goods description"
    )

    duty_fee = st.text_input(
        "Declared Duty Fee",
        placeholder="e.g. 5"
    )

    submitted = st.form_submit_button("Verify Declaration")

# Processing
if submitted:

    if not description.strip():
        st.error("Description is required")
    else:
        incoming_declaration = {
            "hs_code": hs_code.strip(),
            "description": description.strip(),
            "duty_fee": duty_fee.strip()
        }

        st.subheader("Verification Result")

        # STEP 1: HS code validation (same logic as notebook)
        hs_valid = verify_hs_code(incoming_declaration.get("hs_code"))

        if hs_valid:
            with st.spinner("Running HS verification..."):
                response = hscode_verification_toon(incoming_declaration)
        else:
            response = "Invalid HS Code. Not available in the HS dataset."


        st.markdown(
            f"""
            <div style="
                font-family: 'Segoe UI', Arial, sans-serif;
                font-size: 14px;
                line-height: 1.3;
                border: 1px solid #e0e0e0;
                padding: 16px;
                border-radius: 8px;
                background-color: #ffffff;
                box-shadow: 0 1px 2px rgba(0,0,0,0.05);
            ">
                {response}
            </div>
            """,
            unsafe_allow_html=True
        )

Overwriting app.py

In [ ]:
!ngrok config add-authtoken 34rym51lPBarWBiLEqQaJFwJC6Y_Q4MhJeo2286pvmCEE2co

Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml

In [ ]:
from pyngrok import ngrok
!streamlit run app.py &>/dev/null&
url = ngrok.connect(8501)
print("🌐 App running at:", url)

🌐 App running at: NgrokTunnel: "https://alina-uninstalled-aleida.ngrok-free.dev" -> "http://localhost:8501"

# Evaluation

Arabic- Evaluation

In [ ]:
import pandas as pd
import json
import os

# # Paths
# CSV_PATH = "/content/drive/MyDrive/HS_Code_Rag/hs_code_processed_ar_en.csv"
OUTPUT_PATH = "/content/drive/MyDrive/HS_Code_Rag/hs_code_validation_ar.json"

# # Load HS dataset
# df = pd.read_csv(CSV_PATH)

# Keep only required columns for Arabic validation
df = df[["LongDescAr", "final_hs_code", "DutyPercentage"]].dropna()

# # OPTIONAL: remove duplicates
# df = df.drop_duplicates(subset=["LongDescAr", "final_hs_code"])

# OPTIONAL: sample N rows for validation (adjust SAMPLE_SIZE if needed)
SAMPLE_SIZE = 500
df_sample = df.sample(n=min(SAMPLE_SIZE, len(df)), random_state=42)

# Build validation records
validation_data = []
for _, row in df_sample.iterrows():
    validation_data.append({
        "query": row["LongDescAr"].strip(),
        "true_final_hs_code": str(row["final_hs_code"]),
        "true_duty_fee": str(row["DutyPercentage"])
    })

# Save to JSON
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump(validation_data, f, indent=2, ensure_ascii=False)

print(f"Arabic validation dataset created with {len(validation_data)} samples")
print(f"Saved at: {OUTPUT_PATH}")

Arabic validation dataset created with 500 samples
Saved at: /content/drive/MyDrive/HS_Code_Rag/hs_code_validation_ar.json

In [ ]:
import json

VAL_PATH = "/content/drive/MyDrive/HS_Code_Rag/hs_code_validation_ar.json"

with open(VAL_PATH, "r") as f:
    eval_data = json.load(f)

In [ ]:
import re

def extract_final_hs_code(text):
    match = re.search(r"\b\d{12}\b", text)
    return match.group(0) if match else None

def extract_duty_fee(text):
    """
    Extracts the duty fee from the LLM response text.
    Returns the duty fee as a string, or None if not found.
    """
    # Look for a number (integer or decimal) following "Duty" or "duty fee"
    match = re.search(r"(?:Duty fee|duty fee|duty|Fee)\s*[:\-]?\s*(\d+(\.\d+)?)", text, re.IGNORECASE)
    if match:
        return match.group(1)
    return None

**Approach 1**

In [ ]:
TOON_PROMPT = """You are a customs declaration verifier.

You are given multiple retrieved HS records as JSON.
Exactly ONE of these records is authoritative for the given incoming declaration.

Your task has TWO phases:

PHASE 1: HS RECORD SELECTION
- Compare the incoming declaration description with each retrieved HS record.
- Select the ONE HS record that best matches the incoming declaration description.
- Do not explain the selection process.
- Do not mention scores or reasoning.
- The selected HS record becomes the authoritative HS record.
- Ignore all other retrieved records.

PHASE 2: VERIFICATION
Verify the incoming declaration ONLY against the selected authoritative HS record and report each field separately:

HS code:
- If it matches, say: Declaration HS code is correct.
- If not, say: For this description, the declared HS code is incorrect.
  Then provide the correct HS code from the authoritative HS record.
- Never use or mention old_hs_code.

Description:
- If it matches, say: Declaration description is matching.
- If not, say: The declared description is incorrect.
  Then provide the correct description from the authoritative HS record.

Duty fee:
- If it matches, say: Declaration duty fee is correct.
- If not, say: The declared duty fee is incorrect.
  Then provide the correct duty value from the authoritative HS record.

Rules:
- The HS record is final and must not be questioned.
- Do NOT infer missing data.
- Do NOT modify numeric values.
- Do NOT add explanations.
- If a value is not present in the HS record, say: Not available in the HS dataset.
- Output only what is requested below.

OUTPUT FORMAT (strict):

Retrieved Declaration:
hs_code: <value from selected HS record>
description: <value from selected HS record>
duty_fee: <value from selected HS record>

Verification Result:
<HS code verification>
<Description verification>
<Duty fee verification>

HS_RECORDS:
{hs_record}

INCOMING_DECLARATION:
{incoming_declaration}
"""

In [ ]:
import json

def hscode_verification_toon(incoming_declaration):
    """
    Accepts either:
    1) dict -> {"hs_code": ..., "description": ..., "duty_fee": ...}
    2) str  -> description only (used during evaluation)
    """

    # -------- STEP 0: Normalize input type --------
    if isinstance(incoming_declaration, str):
        incoming_declaration = {
            "hs_code": "",
            "description": incoming_declaration,
            "duty_fee": ""
        }

    if not isinstance(incoming_declaration, dict):
        raise ValueError("incoming_declaration must be dict or string")

    # Getting raw description
    query = incoming_declaration.get("description", "")

    # Detect language
    lang = detect_language(query)
    #print("language---:", lang)

    # Normalize text
    if lang == "ar":
        cleaned_query = normalize_arabic_text(query)
    else:
        cleaned_query = normalize_text(query)

    # Update declaration
    incoming_declaration["description"] = cleaned_query

    # Retriever
    retriever = vectorstore.as_retriever(
        search_type="similarity",
        search_kwargs={
            "k": 2,
            "filter": {"lang": lang}
        }
    )

    #Retrieve
    docs = retriever.invoke(cleaned_query)

    if not docs:
        return "No matching HS code found for the given description."

    if not isinstance(docs, list):
        docs = [docs]

    # Format HS record
    hs_record = format_context_toon(docs)

    # Prompt
    prompt = TOON_PROMPT.format(
        hs_record=hs_record,
        incoming_declaration=incoming_declaration
    )

    #print("Prompt")
    #print(prompt)

    return llm(prompt)

In [ ]:
def evaluate_accuracy_ar_en(eval_data):
    total = len(eval_data)
    correct_hs = 0
    correct_duty = 0
    results = []

    for item in eval_data:
        incoming_declaration = {
            "hs_code": item.get("true_final_hs_code", ""),
            "description": item["query"],
            "duty_fee": item.get("true_duty_fee", "")
        }

        # HS code gate check (same as production)
        if verify_hs_code(incoming_declaration["hs_code"]):
            response = hscode_verification_toon(incoming_declaration)
        else:
            response = "Invalid HS Code. Not available in the HS dataset."


        #print("model response----:", response)

        predicted_hs = extract_final_hs_code(response)
        predicted_duty = extract_duty_fee(response)

        #hs_correct = predicted_hs == item["true_final_hs_code"]
        #duty_correct = predicted_duty == str(item["true_duty_fee"])


        hs_correct = (
            predicted_hs is not None
            and str(predicted_hs) == str(item["true_final_hs_code"])
        )

        duty_correct = (
            predicted_duty is not None
            and str(predicted_duty) == str(item["true_duty_fee"])
        )

        #print("predicted_hs---", str(predicted_hs))
        #print("true final hs code---", str(item["true_final_hs_code"]))



        #hs_correct = str(incoming_declaration["hs_code"]) == str(docs.metadata["FinalHSCode"])
        #duty_correct = float(incoming_declaration["duty_fee"]) == float(docs.metadata["DutyPercentage"])

        if hs_correct:
            correct_hs += 1
        if duty_correct:
            correct_duty += 1

        results.append({
            "description": item["query"],
            "true_hs_code": item["true_final_hs_code"],
            "predicted_hs_code": predicted_hs,
            "true_duty_fee": item["true_duty_fee"],
            "predicted_duty_fee": predicted_duty,
            "hs_correct": hs_correct,
            "duty_correct": duty_correct
        })
        import json

    for r in results[:5]:
        print(json.dumps(r, ensure_ascii=False, indent=2))



    return correct_hs / total, correct_duty / total, results

In [ ]:
accuracy_hs, accuracy_duty, detailed_results = evaluate_accuracy_ar_en(
    eval_data
)

print(f"HS Code Accuracy: {accuracy_hs:.2%}")
print(f"Duty Fee Accuracy: {accuracy_duty:.2%}")

predicted_hs--- 841460000000
true final hs code--- 841460000000
predicted_hs--- 950662000003
true final hs code--- 950662000002
predicted_hs--- 400911100000
true final hs code--- 400911100000
predicted_hs--- 480700000001
true final hs code--- 480700000001
predicted_hs--- 080410100000
true final hs code--- 080410100000
predicted_hs--- 290549100000
true final hs code--- 290549100000
predicted_hs--- 320414000000
true final hs code--- 320414000000
predicted_hs--- 440910900000
true final hs code--- 440910900000
predicted_hs--- 600536000000
true final hs code--- 600536000000
predicted_hs--- 251320300001
true final hs code--- 251320300002
predicted_hs--- 070999100000
true final hs code--- 070999100000
predicted_hs--- 843290000002
true final hs code--- 843290000002
predicted_hs--- 851432000000
true final hs code--- 851432000000
predicted_hs--- 284180000001
true final hs code--- 284180000001
predicted_hs--- 290389900001
true final hs code--- 290389900001
predicted_hs--- 580620000000
true final hs code--- 580620000000
predicted_hs--- 380400000000
true final hs code--- 380400000000
predicted_hs--- 030249100000
true final hs code--- 030249100000
predicted_hs--- 540490000006
true final hs code--- 540490000005
predicted_hs--- 710590000000
true final hs code--- 710590000000
predicted_hs--- 400922910000
true final hs code--- 400922910000
predicted_hs--- 210690920001
true final hs code--- 210690920001
predicted_hs--- 160250100000
true final hs code--- 160250100000
predicted_hs--- 551633000000
true final hs code--- 551633000000
predicted_hs--- 261610000007
true final hs code--- 261610000007
predicted_hs--- 871000000002
true final hs code--- 871000000002
predicted_hs--- 441011000001
true final hs code--- 441011000001
predicted_hs--- 291823000003
true final hs code--- 291823000004
predicted_hs--- 470790100000
true final hs code--- 470790100000
predicted_hs--- 520100000000
true final hs code--- 520100000000
predicted_hs--- 570232900002
true final hs code--- 570232900002
predicted_hs--- 843141000001
true final hs code--- 843141000002
predicted_hs--- 611020000001
true final hs code--- 611020000001
predicted_hs--- 010639909999
true final hs code--- 761699990000
predicted_hs--- 010612000002
true final hs code--- 010612000002
predicted_hs--- 842820000000
true final hs code--- 842820000000
predicted_hs--- 950662000001
true final hs code--- 950662000001
predicted_hs--- 711711900000
true final hs code--- 711711900000
predicted_hs--- 290121000000
true final hs code--- 290129300000
predicted_hs--- 330410000000
true final hs code--- 330410000000
predicted_hs--- 151521000000
true final hs code--- 151530000000
predicted_hs--- 890200000001
true final hs code--- 890200000003
predicted_hs--- 860791000000
true final hs code--- 860791000000
predicted_hs--- 130220000000
true final hs code--- 130220000000
predicted_hs--- 293721000001
true final hs code--- 293721000001
predicted_hs--- 382739000004
true final hs code--- 382739000006
predicted_hs--- 284030009999
true final hs code--- 284030009999
predicted_hs--- 610423000000
true final hs code--- 610423000000
predicted_hs--- 851490009999
true final hs code--- 851490009999
predicted_hs--- 920590000001
true final hs code--- 920590000001
predicted_hs--- 860711000000
true final hs code--- 860711000000
predicted_hs--- 490700200001
true final hs code--- 490700200001
predicted_hs--- 844315000000
true final hs code--- 844315000000
predicted_hs--- 281212000000
true final hs code--- 281212000000
predicted_hs--- 442199500000
true final hs code--- 442199500000
predicted_hs--- 270600000023
true final hs code--- 270600000023
predicted_hs--- 961000100001
true final hs code--- 961000100001
predicted_hs--- 870333200000
true final hs code--- 870333200000
predicted_hs--- 284020000003
true final hs code--- 284020000003
predicted_hs--- 051199500000
true final hs code--- 051199500000
predicted_hs--- 482390940000
true final hs code--- 482390940000
predicted_hs--- 611510000001
true final hs code--- 611510000001
predicted_hs--- 950699100000
true final hs code--- 950699100000
predicted_hs--- 842441900000
true final hs code--- 842441900000
predicted_hs--- 294000009999
true final hs code--- 294000009999
predicted_hs--- 591140000000
true final hs code--- 591140000000
predicted_hs--- 170199120001
true final hs code--- 170199120001
predicted_hs--- 020410000003
true final hs code--- 020410000001
predicted_hs--- 291631200001
true final hs code--- 291631200001
predicted_hs--- 540239100000
true final hs code--- 540239100000
predicted_hs--- 940320900005
true final hs code--- 940320900005
predicted_hs--- 940171100000
true final hs code--- 940171100000
predicted_hs--- 251710000004
true final hs code--- 251710000004
predicted_hs--- 121299500001
true final hs code--- 121299500002
predicted_hs--- 291462000000
true final hs code--- 291462000000
predicted_hs--- 732112900000
true final hs code--- 732112900000
predicted_hs--- 091099220000
true final hs code--- 091099220000
predicted_hs--- 902590000001
true final hs code--- 902590000001
predicted_hs--- 630790800000
true final hs code--- 630790800000
predicted_hs--- 271099000001
true final hs code--- 271099000001
predicted_hs--- 490290100001
true final hs code--- 490290100001
predicted_hs--- 271019130011
true final hs code--- 271019130011
predicted_hs--- 901890500003
true final hs code--- 901890500003
predicted_hs--- 848291000000
true final hs code--- 848291000000
predicted_hs--- 570110000003
true final hs code--- 570110000001
predicted_hs--- 848071000000
true final hs code--- 848071000000
predicted_hs--- 732394000000
true final hs code--- 732394000000
predicted_hs--- 610462000004
true final hs code--- 610462000004
predicted_hs--- 580710000000
true final hs code--- 580710000000
predicted_hs--- 360610000000
true final hs code--- 360610000000
predicted_hs--- 293159100005
true final hs code--- 293159240000
predicted_hs--- 620630000003
true final hs code--- 620630000003
predicted_hs--- 490210200001
true final hs code--- 490210200001
predicted_hs--- 170290600001
true final hs code--- 170290600001
predicted_hs--- 630411000000
true final hs code--- 630411000000
predicted_hs--- 620469000010
true final hs code--- 620469000010
predicted_hs--- 030389910006
true final hs code--- 030389910006
predicted_hs--- 030569000000
true final hs code--- 030569000000
predicted_hs--- 848010000000
true final hs code--- 848010000000
predicted_hs--- 720250000000
true final hs code--- 720250000000
predicted_hs--- 940430000001
true final hs code--- 940430000001
predicted_hs--- 060220100000
true final hs code--- 060220100000
predicted_hs--- 420211910000
true final hs code--- 420211910000
predicted_hs--- 260300000018
true final hs code--- 260300000018
predicted_hs--- 284329909999
true final hs code--- 284390000007
predicted_hs--- 620610000001
true final hs code--- 620610000001
predicted_hs--- 840734100000
true final hs code--- 840734100000
predicted_hs--- 482390999999
true final hs code--- 482390999999
predicted_hs--- 190590109999
true final hs code--- 190590109999
predicted_hs--- 300610400000
true final hs code--- 300610100000
predicted_hs--- 481099000000
true final hs code--- 481092000000
predicted_hs--- 902139200003
true final hs code--- 902139200003
predicted_hs--- 370297000000
true final hs code--- 370297000000
predicted_hs--- 560410000003
true final hs code--- 560410000003
predicted_hs--- 330720000000
true final hs code--- 330720000000
predicted_hs--- 610329000001
true final hs code--- 610329000001
predicted_hs--- 350219000000
true final hs code--- 350219000000
predicted_hs--- 320910909999
true final hs code--- 320910909999
predicted_hs--- 250810000002
true final hs code--- 250810000002
predicted_hs--- 610729000001
true final hs code--- 610729000001
predicted_hs--- 400931140000
true final hs code--- 400931140000
predicted_hs--- 070690400000
true final hs code--- 070920000000
predicted_hs--- 730539000000
true final hs code--- 730539000000
predicted_hs--- 293148000000
true final hs code--- 293148000000
predicted_hs--- 391000000001
true final hs code--- 391000000001
predicted_hs--- 851390000000
true final hs code--- 851390000000
predicted_hs--- 811300000004
true final hs code--- 811300000004
predicted_hs--- 030111000000
true final hs code--- 030111000000
predicted_hs--- 843120000002
true final hs code--- 843120000002
predicted_hs--- 150430900000
true final hs code--- 150430900000
predicted_hs--- 610990000002
true final hs code--- 610990009999
predicted_hs--- 481920100003
true final hs code--- 481920100003
predicted_hs--- 281640000004
true final hs code--- 281640000005
predicted_hs--- 271012419999
true final hs code--- 271012419999
predicted_hs--- 292800000006
true final hs code--- 292800000006
predicted_hs--- 200819190000
true final hs code--- 200819190000
predicted_hs--- 340590200000
true final hs code--- 340590200000
predicted_hs--- 720719000001
true final hs code--- 720719000002
predicted_hs--- 292990900001
true final hs code--- 292990900001
predicted_hs--- 440341900000
true final hs code--- 440341900000
predicted_hs--- 270791000000
true final hs code--- 270791000000
predicted_hs--- 850660100000
true final hs code--- 850660100000
predicted_hs--- 190300000000
true final hs code--- 190300000000
predicted_hs--- 850120000001
true final hs code--- 850120000001
predicted_hs--- 842129100000
true final hs code--- 842129100000
predicted_hs--- 252310000001
true final hs code--- 252310000001
predicted_hs--- 854060000000
true final hs code--- 854060000000
predicted_hs--- 750890200000
true final hs code--- 750890200000
predicted_hs--- 180400000001
true final hs code--- 180400000001
predicted_hs--- 621420900004
true final hs code--- 621420900004
predicted_hs--- 731290100000
true final hs code--- 731290100000
predicted_hs--- 730900920001
true final hs code--- 730900920001
predicted_hs--- 730230000002
true final hs code--- 730230000002
predicted_hs--- 271019139999
true final hs code--- 271019139999
predicted_hs--- 600633000000
true final hs code--- 600633000000
predicted_hs--- 293090120000
true final hs code--- 293090120000
predicted_hs--- 720827000003
true final hs code--- 720827000003
predicted_hs--- 732181900000
true final hs code--- 732181900000
predicted_hs--- 831000500001
true final hs code--- 831000500001
predicted_hs--- 551441000000
true final hs code--- 551441000000
predicted_hs--- 841583209999
true final hs code--- 841583209999
predicted_hs--- 848180100000
true final hs code--- 848180100000
predicted_hs--- 080410210000
true final hs code--- 080410210000
predicted_hs--- 110610210000
true final hs code--- 110610210000
predicted_hs--- 920210000002
true final hs code--- 920210000002
predicted_hs--- 271019110001
true final hs code--- 271019110004
predicted_hs--- 252010200001
true final hs code--- 252010200001
predicted_hs--- 870880000003
true final hs code--- 870880000001
predicted_hs--- 846420000001
true final hs code--- 846420000002
predicted_hs--- 271019980001
true final hs code--- 271019980001
predicted_hs--- 842290000000
true final hs code--- 842230300000
predicted_hs--- 071340000001
true final hs code--- 071340000001
predicted_hs--- 321590910000
true final hs code--- 321590910000
predicted_hs--- 441520000001
true final hs code--- 441520000001
predicted_hs--- 300443200000
true final hs code--- 300443200000
predicted_hs--- 330300200000
true final hs code--- 330300200000
predicted_hs--- 730650100000
true final hs code--- 730650100000
predicted_hs--- 761010900002
true final hs code--- 761010900002
predicted_hs--- 310420000001
true final hs code--- 310420000001
predicted_hs--- 300431110000
true final hs code--- 300431110000
predicted_hs--- 620610000003
true final hs code--- 620610000003
predicted_hs--- 283319000000
true final hs code--- 283319000000
predicted_hs--- 392690990006
true final hs code--- 392690990006
predicted_hs--- 810490300006
true final hs code--- 810490300006
predicted_hs--- 410330000000
true final hs code--- 410330000000
predicted_hs--- 442199600000
true final hs code--- 442199600000
predicted_hs--- 030346000000
true final hs code--- 030346000000
predicted_hs--- 848110000000
true final hs code--- 848110000000
predicted_hs--- 570390900004
true final hs code--- 570390900004
predicted_hs--- 381519900000
true final hs code--- 381519900000
predicted_hs--- 940320900008
true final hs code--- 940320900027
predicted_hs--- 040110920000
true final hs code--- 040110920000
predicted_hs--- 250100100012
true final hs code--- 250100100010
predicted_hs--- 841459300000
true final hs code--- 841459300000
predicted_hs--- 481149000000
true final hs code--- 481149000000
predicted_hs--- 190220200000
true final hs code--- 190220100000
predicted_hs--- 030256000000
true final hs code--- 030256000000
predicted_hs--- 441011000001
true final hs code--- 441011000003
predicted_hs--- 846789000000
true final hs code--- 846789000000
predicted_hs--- 811249000000
true final hs code--- 811249000000
predicted_hs--- 670419000005
true final hs code--- 670419000005
predicted_hs--- 491000000002
true final hs code--- 491000000002
predicted_hs--- 190420290002
true final hs code--- 190420290002
predicted_hs--- 420212100003
true final hs code--- 420212100003
predicted_hs--- 844511000000
true final hs code--- 844511000000
predicted_hs--- 520534000000
true final hs code--- 520534000000
predicted_hs--- 843319000000
true final hs code--- 843319000000
predicted_hs--- 080720000000
true final hs code--- 080720000000
predicted_hs--- 340311000000
true final hs code--- 340311000000
predicted_hs--- 271091900000
true final hs code--- 271091900000
predicted_hs--- 020430000001
true final hs code--- 020430000001
predicted_hs--- 846781000000
true final hs code--- 846781000000
predicted_hs--- 382731000000
true final hs code--- 382731000000
predicted_hs--- 010639909999
true final hs code--- 680990990000
predicted_hs--- 870350000001
true final hs code--- 870350000001
predicted_hs--- 620819000001
true final hs code--- 620819000001
predicted_hs--- 620349000010
true final hs code--- 620349000010
predicted_hs--- 251910000000
true final hs code--- 251910000000
predicted_hs--- 440799900006
true final hs code--- 440799900002
predicted_hs--- 291539009999
true final hs code--- 291539009999
predicted_hs--- 843131109999
true final hs code--- 843131109999
predicted_hs--- 845959000000
true final hs code--- 845959000000
predicted_hs--- 070952000000
true final hs code--- 070952000000
predicted_hs--- 854790000002
true final hs code--- 854790000002
predicted_hs--- 420329000002
true final hs code--- 420329000002
predicted_hs--- 920590000001
true final hs code--- 920930009999
predicted_hs--- 380891990002
true final hs code--- 380891990002
predicted_hs--- 250490000001
true final hs code--- 250490000001
predicted_hs--- 480550000000
true final hs code--- 480550000000
predicted_hs--- 271019130009
true final hs code--- 271019130009
predicted_hs--- 290433000000
true final hs code--- 290433000000
predicted_hs--- 630629900000
true final hs code--- 630629900000
predicted_hs--- 950621000000
true final hs code--- 950621000000
predicted_hs--- 283429900003
true final hs code--- 283429900003
predicted_hs--- 021012000000
true final hs code--- 021012000000
predicted_hs--- 902139200008
true final hs code--- 902139200008
predicted_hs--- 420310000000
true final hs code--- 420310000000
predicted_hs--- 790200000001
true final hs code--- 790200000001
predicted_hs--- 620819000006
true final hs code--- 620819000006
predicted_hs--- 570321000000
true final hs code--- 570321000000
predicted_hs--- 291469009999
true final hs code--- 291469009999
predicted_hs--- 030469000000
true final hs code--- 030469000000
predicted_hs--- 290519900001
true final hs code--- 290519900001
predicted_hs--- 830241200000
true final hs code--- 830241200000
predicted_hs--- 700100000001
true final hs code--- 700100000001
predicted_hs--- 481159000003
true final hs code--- 481159000003
predicted_hs--- 010129200001
true final hs code--- 010129200001
predicted_hs--- 490199400002
true final hs code--- 490199400002
predicted_hs--- 841869900001
true final hs code--- 841869900001
predicted_hs--- 850440110000
true final hs code--- 850440110000
predicted_hs--- 260300000010
true final hs code--- 260300000010
predicted_hs--- 271390000003
true final hs code--- 271390000003
predicted_hs--- 930120000002
true final hs code--- 930120000002
predicted_hs--- 580127000000
true final hs code--- 580127000000
predicted_hs--- 551311000000
true final hs code--- 551311000000
predicted_hs--- 590700110000
true final hs code--- 590700110000
predicted_hs--- 290374000000
true final hs code--- 290373000000
predicted_hs--- 410692000000
true final hs code--- 410692000000
predicted_hs--- 282570000002
true final hs code--- 282570000002
predicted_hs--- 551211000000
true final hs code--- 551211000000
predicted_hs--- 321410930000
true final hs code--- 321410930000
predicted_hs--- 841940000000
true final hs code--- 841940000000
predicted_hs--- 844842000002
true final hs code--- 844842000002
predicted_hs--- 281910000000
true final hs code--- 281910000000
predicted_hs--- 520419000000
true final hs code--- 520419000000
predicted_hs--- 060420200000
true final hs code--- 060420200000
predicted_hs--- 460290169999
true final hs code--- 460290169999
predicted_hs--- 170220000000
true final hs code--- 170220000000
predicted_hs--- 844720000000
true final hs code--- 844720000000
predicted_hs--- 300420000001
true final hs code--- 300420000001
predicted_hs--- 880622900000
true final hs code--- 880622900000
predicted_hs--- 160100300014
true final hs code--- 160100300014
predicted_hs--- 880623200000
true final hs code--- 880623200000
predicted_hs--- 282510000002
true final hs code--- 282510000002
predicted_hs--- 630790300000
true final hs code--- 630790300000
predicted_hs--- 940320300000
true final hs code--- 846261000000
predicted_hs--- 251200000001
true final hs code--- 251200000001
predicted_hs--- 321590200001
true final hs code--- 321590200001
predicted_hs--- 540419100000
true final hs code--- 540419100000
predicted_hs--- 901600000000
true final hs code--- 901600000000
predicted_hs--- 900630000005
true final hs code--- 900630000005
predicted_hs--- 291732000000
true final hs code--- 291732000000
predicted_hs--- 880529000002
true final hs code--- 880529000002
predicted_hs--- 870423300000
true final hs code--- 870423300000
predicted_hs--- 130219300000
true final hs code--- 130219300000
predicted_hs--- 440791200000
true final hs code--- 440791200000
predicted_hs--- 230250100000
true final hs code--- 230250100000
predicted_hs--- 283410909999
true final hs code--- 283410909999
predicted_hs--- 721250000002
true final hs code--- 721250000002
predicted_hs--- 271019930001
true final hs code--- 271019930001
predicted_hs--- 250860000001
true final hs code--- 250860000002
predicted_hs--- 252800000003
true final hs code--- 252800000003
predicted_hs--- 680422000000
true final hs code--- 680422000000
predicted_hs--- 711021000000
true final hs code--- 711021000000
predicted_hs--- 570249900003
true final hs code--- 570249900003
predicted_hs--- 151519000000
true final hs code--- 151519000000
predicted_hs--- 310250100000
true final hs code--- 310250100000
predicted_hs--- 300242000000
true final hs code--- 300242000000
predicted_hs--- 310490110000
true final hs code--- 310490110000
predicted_hs--- 291419000001
true final hs code--- 291419000001
predicted_hs--- 843120000001
true final hs code--- 843120000001
predicted_hs--- 620349000007
true final hs code--- 620349000007
predicted_hs--- 830590000000
true final hs code--- 830590000000
predicted_hs--- 170290500002
true final hs code--- 170290500002
predicted_hs--- 901380100001
true final hs code--- 901380100002
predicted_hs--- 293110100000
true final hs code--- 293110100000
predicted_hs--- 291818000000
true final hs code--- 291818000000
predicted_hs--- 750511000001
true final hs code--- 750511000002
predicted_hs--- 831130000000
true final hs code--- 831130000000
predicted_hs--- 292112000000
true final hs code--- 292112000000
predicted_hs--- 910199000000
true final hs code--- 910199000000
predicted_hs--- 284290000002
true final hs code--- 284290000002
predicted_hs--- 290420900012

**English-Arabic Evaluation**

In [ ]:
import pandas as pd
import json

OUTPUT_PATH = "/content/drive/MyDrive/HS_Code_Rag/hs_code_validation_ar_en.json"

# Keep required columns
df = df[["LongDescAr", "LongDescEn", "final_hs_code", "DutyPercentage"]].dropna()

# Optional: remove duplicates per language
df = df.drop_duplicates(
    subset=["LongDescAr", "LongDescEn", "final_hs_code", "DutyPercentage"]
)

# SAMPLE SIZE
SAMPLE_SIZE_PER_LANG = 200

# Sample Arabic
df_ar = df.sample(
    n=min(SAMPLE_SIZE_PER_LANG, len(df)),
    random_state=42
)

# Sample English (different seed to avoid overlap bias)
df_en = df.sample(
    n=min(SAMPLE_SIZE_PER_LANG, len(df)),
    random_state=99
)

validation_data = []

#Build Arabic records
for _, row in df_ar.iterrows():
    validation_data.append({
        "query": row["LongDescAr"].strip(),
        "true_final_hs_code": str(row["final_hs_code"]),
        "true_duty_fee": str(row["DutyPercentage"])
    })

#Build English records
for _, row in df_en.iterrows():
    validation_data.append({
        "query": row["LongDescEn"].strip(),
        "true_final_hs_code": str(row["final_hs_code"]),
        "true_duty_fee": str(row["DutyPercentage"])
    })

# Save JSON
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump(validation_data, f, indent=2, ensure_ascii=False)

print(f"Validation dataset created with {len(validation_data)} samples")
print(f"Arabic samples: {len(df_ar)}")
print(f"English samples: {len(df_en)}")
print(f"Saved at: {OUTPUT_PATH}")

Validation dataset created with 400 samples
Arabic samples: 200
English samples: 200
Saved at: /content/drive/MyDrive/HS_Code_Rag/hs_code_validation_ar_en.json

In [ ]:
accuracy_hs, accuracy_duty, detailed_results = evaluate_accuracy_ar_en(
    eval_data
)

print(f"HS Code Accuracy: {accuracy_hs:.2%}")
print(f"Duty Fee Accuracy: {accuracy_duty:.2%}")

{
  "description": "اجهزه اغطيه شافطه او مبدله للهواء، لايتجاوز مقاس اكبر جانب افقي لها سم، وان كانت مزوده بمنقيات هواء فلاتر",
  "true_hs_code": "841460000000",
  "predicted_hs_code": "841460000000",
  "true_duty_fee": "5",
  "predicted_duty_fee": "5",
  "hs_correct": true,
  "duty_correct": true
}
{
  "description": "كرات التنس العشبي قابله للنفخ كرات سله",
  "true_hs_code": "950662000002",
  "predicted_hs_code": "950662000002",
  "true_duty_fee": "5",
  "predicted_duty_fee": "5",
  "hs_correct": true,
  "duty_correct": true
}
{
  "description": "انابيب ومواسير وخراطيم من مطاط مبركن مهياه لمعدات النقل غير مقواه او متحده بطريقه اخري بمواد اخر، دون لوازم",
  "true_hs_code": "400911100000",
  "predicted_hs_code": "400911100000",
  "true_duty_fee": "5",
  "predicted_duty_fee": "5",
  "hs_correct": true,
  "duty_correct": true
}
{
  "description": "ورق وورق مقوي، مجمع طبقات مسطحه باللصق ، غير مطلي السطح ولا مشرب، وان كان مقوي من الداخل، لفات او صفايح ورق مجمع مصنع بلصق طبقات مسطحه من الورق او الورق المقوي معا بماده لاصقه ، غير مطلي السطح ولا مشرب، وان كان مقوي من الداخل، لفات",
  "true_hs_code": "480700000001",
  "predicted_hs_code": "480700000001",
  "true_duty_fee": "5",
  "predicted_duty_fee": "5",
  "hs_correct": true,
  "duty_correct": true
}
{
  "description": "تمور طازجه او مبرده",
  "true_hs_code": "080410100000",
  "predicted_hs_code": "080410100000",
  "true_duty_fee": "0",
  "predicted_duty_fee": "0",
  "hs_correct": true,
  "duty_correct": true
}
HS Code Accuracy: 90.80%
Duty Fee Accuracy: 92.00%